SmartCity.WebUI/Controllers/HomeFeedbackController.cs
using SmartCity.Common;
using SmartCity.Domain.Abstract;
using SmartCity.Domain.Entities;
using SmartCity.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartCity.WebUI.Controllers
{
    public class HomeFeedbackController : BaseController
    {

        private IFeedBackInfo FeedBackService;

        public HomeFeedbackController(IFeedBackInfo FeedBackInfo)
        {
            this.FeedBackService = FeedBackInfo;
        }
        // GET: Feedback
        public ActionResult FeedBackIndex()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            var Model = new FeedBackModel();
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
        public ActionResult FeedBackAdd(string Content)
        {

            if (CurrentUserInfo != null)
            {
                var model = new FeedBack();
                model.ComplaintContent = Content;
                model.CreateTime = DateTime.Now;
                model.OwnerID = CurrentUserInfo.OwnerID;
                var result = FeedBackService.FeedBackAdd(model);
                if (result)
                {
                    return Json(new { IsSuccess = 0, Message = "谢谢你的反馈，我们确定后会与你电话联系！" });
                }
                return Json(new { IsSuccess = 1, Message = "反馈失败，请稍后重试！" });
            }
            return Json(new { IsSuccess = 1, Message = "对不起，你还未登陆，不能进行意见反馈！" });
        

        }
    }
}

SmartCity.WebUI/Controllers/HomeNewsController.cs
using SmartCity.Common;
using SmartCity.Domain.Abstract;
using SmartCity.Domain.Entities;
using SmartCity.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartCity.WebUI.Controllers
{
    public class HomeNewsController : BaseController
    {
        #region 字段 构造函数
        /// <summary>
        /// 日志记录
        /// </summary>
        private INoticeInfo NewsInfoService;
        private IPostsInfo PostInfoService;
        private IUserInfo UserInfoService;
        private IReviewInfo ReviewInfoService;
        public HomeNewsController(INoticeInfo NewsInfo, IPostsInfo PostInfo, IUserInfo UserInfos, IReviewInfo ReviewInfo)
        {
            this.NewsInfoService = NewsInfo;
            this.PostInfoService = PostInfo;
            this.UserInfoService = UserInfos;
            this.ReviewInfoService = ReviewInfo;
        }
        #endregion
        // GET: HomeNews
        public ActionResult HomeNewsList()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            //获取通知公告
            var Model = new HomeNewsModel();
            var result = NewsInfoService.GetNewsListByPublished().ToList();
            Model.NewsItems = result;
            int PageCount = 0;
            //获取热门帖子
            var HotPostsModel = PostInfoService.GetHotPostsInfo().ToList();
            //获取标签
            var PostsType = PostInfoService.SerachPostsType().ToList();
            //获取最新评论
            var LatestReviews = ReviewInfoService.GetLatestReviews().ToList();
            Model.HotPostsItems = HotPostsModel;
            Model.PostsTypeItems = PostsType;
            Model.LatestReviewsItems = LatestReviews;
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            Model.PageCount = PageCount;
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }

        public ActionResult HomeNewsIndex(int id)
        {
            var model = CurrentUserInfo;
            var Model = new HomeNewsModel();
            //获取通知公告
            var HomeNewIndex = NewsInfoService.GetNoticeInfoByID(id);
            //获取热门帖子
            var HotPostsModel = PostInfoService.GetHotPostsInfo().ToList();
            //获取标签
            var PostsType = PostInfoService.SerachPostsType().ToList();
            //获取最新评论
            var LatestReviews = ReviewInfoService.GetLatestReviews().ToList();
            Model.NewsItems = HomeNewIndex.ToList();
            Model.HotPostsItems = HotPostsModel;
            Model.PostsTypeItems = PostsType;
            Model.LatestReviewsItems = LatestReviews;
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
    }
}

SmartCity.WebUI/Controllers/HomePageController.cs
using SmartCity.Common;
using SmartCity.Common.log4net.Ext;
using SmartCity.Domain.Abstract;
using SmartCity.Domain.Concrete;
using SmartCity.Domain.Entities;
using SmartCity.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SmartCity.WebUI.Controllers
{
    public class HomePageController : BaseController
    {
        #region 字段 构造函数
        /// <summary>
        /// 日志记录
        /// </summary>
        public IExtLog log = ExtLogManager.GetLogger("dblog");
        private INoticeInfo NewsInfoService;
        private IPostsInfo PostInfoService;
        private IUserInfo UserInfoService;
        private IReviewInfo ReviewInfoService;
        public HomePageController(INoticeInfo NewsInfo, IPostsInfo PostInfo, IUserInfo UserInfos, IReviewInfo ReviewInfo)
        {
            this.NewsInfoService = NewsInfo;
            this.PostInfoService = PostInfo;
            this.UserInfoService = UserInfos;
            this.ReviewInfoService = ReviewInfo;
        }
        #endregion
        // GET: HomePage
        public ActionResult Index()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            //获取通知公告
            var Model = new HomePageModel();
            var result = NewsInfoService.GetNewsListByPublished().ToList();
            Model.NewsItems = result;
            int PageCount = 0;
            //获取论坛
            var PostsModel = PostInfoService.GetPostsInfoListByPage(PageCounts, 1, out PageCount).ToList();
            //获取热门帖子
            var HotPostsModel = PostInfoService.GetHotPostsInfo().ToList();
            //获取标签
            var PostsType = PostInfoService.SerachPostsType().ToList();
            //获取最新评论
            var LatestReviews = ReviewInfoService.GetLatestReviews().ToList();

            Model.HotPostsItems = HotPostsModel;
            Model.PostsItems = PostsModel;
            Model.PostsTypeItems = PostsType;
            Model.LatestReviewsItems = LatestReviews;
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            Model.PageCount = PageCount;
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
        public ActionResult GetPostInfoByPage(int Curr)
        {
            int PageCount = 0;
            var model = PostInfoService.GetPostsInfoListByPage(PageCounts, Curr, out PageCount).ToList();
            return Json(new { IsSuccess = 0, Items = model });
        }
        public ActionResult EditPassword()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            var Model = new FeedBackModel();
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
        [HttpPost]
        public ActionResult EditUserPassword(string oldPassWord, string NewPassWord, string NewPassWord1)
        {
            if (CurrentUserInfo != null)
            {
                if (NewPassWord !=NewPassWord1)
                {
                    var result = UserInfoService.EditUserPassword(CurrentUserInfo.OwnerID, oldPassWord, NewPassWord);
                    if (result)
                    {
                        return Json(new { IsSuccess = 0, Message = "修改成功！" });
                    }
                    return Json(new { IsSuccess = 1, Message = "修改失败，请稍后重试！" });
                }
                return Json(new { IsSuccess = 1, Message = "对不起，你两次输入的密码不一致！" });

            }
            return Json(new { IsSuccess = 1, Message = "对不起，你还未登陆，不能进行在线报修！" });
        }
    }
}

SmartCity.WebUI/Controllers/HomePostsController.cs
using SmartCity.Common;
using SmartCity.Domain.Abstract;
using SmartCity.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartCity.WebUI.Models;

namespace SmartCity.WebUI.Controllers
{
    public class HomePostsController : BaseController
    {
        #region 字段 构造函数
        /// <summary>
        /// 日志记录
        /// </summary>
        private INoticeInfo NewsInfoService;
        private IPostsInfo PostInfoService;
        private IUserInfo UserInfoService;
        private IReviewInfo ReviewInfoService;
        public HomePostsController(INoticeInfo NewsInfo, IPostsInfo PostInfo, IUserInfo UserInfos, IReviewInfo ReviewInfo)
        {
            this.NewsInfoService = NewsInfo;
            this.PostInfoService = PostInfo;
            this.UserInfoService = UserInfos;
            this.ReviewInfoService = ReviewInfo;
        }
        #endregion

        // GET: Posts
        public ActionResult Index(string PostsLable)
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            //获取通知公告
            var Model = new PostsModel();
            int PageCount = 0;
            //获取论坛
            var PostsModel = PostInfoService.GetPostsInfoListByPageAndType(10, 1, out PageCount,PostsLable).ToList();
            //获取热门帖子
            var HotPostsModel = PostInfoService.GetHotPostsInfo().ToList();
            //获取标签
            var PostsType = PostInfoService.SerachPostsType().ToList();
            //获取最新评论
            var LatestReviews = ReviewInfoService.GetLatestReviews().ToList();

            Model.HotPostsItems = HotPostsModel;
            Model.PostsItems = PostsModel;
            Model.PostsTypeItems = PostsType;
            Model.LatestReviewsItems = LatestReviews;
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            Model.PageCount = PageCount;
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }

        public ActionResult HomePostAllList()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            //获取通知公告
            var Model = new PostsModel();
            int PageCount = 0;
            //获取论坛
            var PostsModel = PostInfoService.GetPostsInfoListByPage(10, 1, out PageCount).ToList();
            //获取热门帖子
            var HotPostsModel = PostInfoService.GetHotPostsInfo().ToList();
            //获取标签
            var PostsType = PostInfoService.SerachPostsType().ToList();
            //获取最新评论
            var LatestReviews = ReviewInfoService.GetLatestReviews().ToList();

            Model.HotPostsItems = HotPostsModel;
            Model.PostsItems = PostsModel;
            Model.PostsTypeItems = PostsType;
            Model.LatestReviewsItems = LatestReviews;
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = " ";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            Model.PageCount = PageCount;
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
        public ActionResult GetPostInfoByPage(int Curr,string PotsLaber)
        {
            int PageCount = 0;
            var model = PostInfoService.GetPostsInfoListByPageAndType(PageCounts, Curr, out PageCount,PotsLaber).ToList();
            return Json(new { IsSuccess = 0, Items = model });
        }
    }
}

SmartCity.WebUI/Controllers/HomeRepairController.cs
using SmartCity.Common;
using SmartCity.Domain.Abstract;
using SmartCity.Domain.Entities;
using SmartCity.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartCity.WebUI.Controllers
{
    /// <summary>
    /// 报修控制器
    /// </summary>
    public class HomeRepairController : BaseController
    {
        private IRepairInfo RepairInfoService;

        public HomeRepairController(IRepairInfo RepairInfo)
        {
            this.RepairInfoService = RepairInfo;
        }
        // GET: HomeRepair
        public ActionResult RepairInfoAdd()
        {
            var model = SessionHelper.GetSession("HomeUserInfo");
            var Model = new RepairInfoModel();
            Model.Title1 = "Hi, 请登录";
            Model.Tiltle2 = "";
            Model.TitleUrL1 = "#";
            Model.TitleUrl2 = "#";
            if (model != null)
            {
                var models = model as User;
                Model.Title1 = "Hi, 欢迎你";
                Model.Tiltle2 = models.UserName;
            }
            return View(Model);
        }
        public ActionResult RepairInfoAddForUser(string RepairName, string RepairType, string RepairContent)
        {
            if (CurrentUserInfo != null)
            {

                var model = new Repair();
                model.RepairName = RepairName;
                model.RepairType = Convert.ToInt32(Enum.Parse(typeof(SmartCity.WebUI.Infrastructure.EnumData.RepairType), RepairType));
                model.RepairContent = RepairContent;
                model.OwnerID = CurrentUserInfo.OwnerID;
                //model.MaintenanceStatus = 3;
                model.CreateTime = DateTime.Now;
                var result = RepairInfoService.RepairInfoAdd(model);
                if (result)
                {
                    return Json(new { IsSuccess = 0, Message = "谢谢你的反馈，我们确定后会与你电话联系！" });
                }
                return Json(new { IsSuccess = 1, Message = "报修失败，请稍后重试！" });
            }
            return Json(new { IsSuccess = 1, Message = "对不起，你还未登陆，不能进行在线报修！" });


        }
    }
}

SmartCity.WebUI/Views/HomeFeedback/FeedBackIndex.cshtml
@model SmartCity.WebUI.Models.FeedBackModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>意见反馈页</title>
    <link href="~/Content/HomeStyle/um.css" id="um-css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/HomeStyle/font-awesome.css" id="fa-css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/layui.css" rel="stylesheet" />
    <link href="~/Content/HomeStyle/style.css" id="style-css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/HomeStyle/share.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Content/HomeStyle/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/HomeStyle/jquery.js"></script>

    <script src="~/Content/HomeStyle/hm.js"></script>
    <script>
        window._deel = { name: '翠竹林小区物业系统', url: '#', ajaxpager: '', commenton: 0, roll: [0] }
    </script>
</head>
<body>
    <header id="masthead" class="site-header">
        <nav id="top-header">
            <div class="top-nav">
                <div id="user-profile">
                    <span class="nav-set">
                        <span class="nav-login">
                            <a id="Tile1" href="@Model.TitleUrL1" class="user-login">@Model.Title1</a>&nbsp; &nbsp;<a id="Title2" href="@Model.TitleUrl2" class="signup-loader">@Model.Tiltle2</a>
                        </span>
                    </span>
                </div>
                <div class="menu-container">
                    <ul id="menu-%e5%a4%b4%e9%83%a8" class="top-menu">
                        <a target="_blank" href="#">关于我们</a> |
                        <a target="_blank" href="#">联系我们</a>
                    </ul>
                </div>
            </div>
        </nav>
        <div id="nav-header" class="fixed shadow">
            <div id="top-menu">
                <div id="top-menu_1">
                    <span class="nav-search"><i class="fa fa-search"></i></span> <span class="nav-search_1"><a href="#"><i class="fa fa-navicon"></i></a></span>
                    <hgroup class="logo-site" style="margin-top: 5px;">
                        <h1 class="site-title"> <a href="#"><img src="~/Content/HomeStyle/logo.png" alt="小区物业管理"></a></h1>
                    </hgroup>
                    <div id="site-nav-wrap">
                        <nav id="site-nav" class="main-nav">
                            <div>
                                <ul class="down-menu nav-menu">
                                    <li id="menu-item-23" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-204"><a href="@Url.Action("Index", "HomePage")" style="padding: 10px;">首页</a></li>
                                    <li id="menu-item-193" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-193">
                                        <a href="@Url.Action("HomeNewsList","HomeNews")" style="padding: 10px;">通知公告</a>
                                    </li>
                                    <li id="menu-item-204" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-204"><a href="@Url.Action("HomePostAllList", "HomePosts")" style="padding: 10px;">在线交流</a></li>
                                    <li id="menu-item-201" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-201"><a href="@Url.Action("RepairInfoAdd", "HomeRepair")" style="padding: 10px;">在线报修</a></li>
                                    <!--<li id="menu-item-202" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-202"><a href="#" style="padding: 10px;">网站运营</a></li>-->
                                    <li id="menu-item-205" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-205"><a href="#" style="padding: 10px;">关于我们</a></li>
                                    <li id="menu-item-212" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-212"><a href="@Url.Action("FeedBackIndex","HomeFeedback")" style="padding: 10px;">意见反馈</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <nav>
            <ul class="nav_sj" id="nav-search_1">
                <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-204"><a href="@Url.Action("Index", "HomePage")">首页</a></li>
                <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-193">
                    <a href="@Url.Action("HomeNewsList","HomeNews")">通知公告</a>
                </li>
                <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-204"><a href="@Url.Action("HomePostAllList", "HomePosts")">在线交流</a></li>
                <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-201"><a href="@Url.Action("RepairInfoAdd", "HomeRepair")">在线报修</a></li>
                <!--<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-202"><a href="#">网站运营</a></li>-->
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-205"><a href="#">关于我们</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-212"><a href="@Url.Action("FeedBackIndex","HomeFeedback")">意见反馈</a></li>
            </ul>
        </nav>
    </header>
    <div id="search-main">
        <div id="searchbar">
            <form id="searchform" action="#" method="get">
                <input id="s" type="text" required="" placeholder="输入搜索内容" name="s" value="">
                <button id="searchsubmit" type="submit">搜索</button>
            </form>
        </div>
        <div id="searchbar">
            <form id="searchform" target="_blank" action="#" method="get">
                <input type="hidden" name="entry" value="1">
                <input class="swap_value" name="q" placeholder="输入百度站内搜索关键词">
                <button id="searchsubmit" type="submit">百度</button>
            </form>
        </div>
        <div class="clear"></div>
    </div>
    <section class="container">
        <div class="speedbar"></div>
        <div class="pagewrapper clearfix">
            <div class="pagecontent"  style="margin-left:0px;">
                <header class="pageheader clearfix">
                    <h1 class="pull-left">
                        <a href="@Url.Action("FeedBackIndex", "HomeFeedBack")">意见反馈</a>
                    </h1>
                    <div class="pull-right">
                    </div>
                </header>
                <article class="article-content"></article>
                <ul class="submit-form">
                    <li>
                        <strong>反馈内容</strong>
                        <textarea id="tougao-content" rows="12" class="input-block-level" placeholder="写点什么..."></textarea>
                        <p class="text-error hide"></p>
                    </li>
                </ul>
                <div class="text-error"></div>
                <button id="tougao-submit" class="btn btn-primary"><i class="fa fa-check-square-o"></i> 立即提交</button>
            </div>
        </div>
    </section>
    <div class="branding branding-black">
        <div class="container_f">
            <h2>高效，专业，小区管理系统</h2><a class="btn btn-lg" href="#" target="_blank">联系我们</a>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-inner">
            <p>
                <a href="#" title="翠竹林">翠竹林小区物业管理</a> 版权所有，保留一切权利 翠竹林小区物业管理&nbsp;&nbsp;
            </p>
            <p>小区物业管理 by <a title="翠竹林" href="#">翠竹林</a> </p>
        </div>
    </footer>
    <script type="text/javascript" src="~/Content/HomeStyle/um.js"></script>
    <script type="text/javascript" src="~/Content/HomeStyle/wp-embed.min.js"></script>
    <script src="~/Content/layui.js"></script>
    <script type="text/javascript">
        layui.use(['laypage', 'layer', "jquery"], function () {
            var laypage = layui.laypage, layer = layui.layer, $ = layui.jquery;

        });
        $('#tougao-submit').click(function () {
            var param = {};
            param.Content = $("#tougao-content").val();
            $.ajax({
                type: 'POST',
                url: '/HomeFeedback/FeedbackAdd',
                data: param,
                success: function (result) {
                    if (result.IsSuccess == 0) {
                        window.location.reload();
                    } else {
                        layer.msg(result.Message, { icon: 2 });
                    }
                },
                datatype: "json",
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    layer.msg('添加失败，请稍后重试！', { icon: 2 });
                }
            });
            param = null;
        });
    </script>
</body>
</html>